import Link from "next/link";

import { DELETION_RETAINED_FIELDS, RETENTION_SCHEDULE, hasUnenforcedWindow, retentionLine } from "@/features/legal/retention";
import { getNavigationHref } from "@/features/shell/capabilities";
import type { Locale } from "@/lib/preferences";

import { ExportControl } from "./export-control";
import { GlobalSignOut } from "./global-sign-out";
import { PRIVACY_CATEGORIES, WITHHELD_TABLES } from "./enumeration";
import { getPrivacyCopy } from "./copy";
import type { PrivacyCensus } from "./census";

/**
 * Privacidade e dados, inside Ajustes — `2O-PRIVACY-001` … `-010`.
 *
 * ## Counts only, and that is what makes T-4 unreachable
 *
 * `2O-PRIVACY-003` allows a category to *"state how many rows exist without
 * revealing content"*, and `ProtectedContent` governs anything rendered beyond
 * a count. Nothing here is rendered beyond a count: the census sends
 * `head: true` requests, so no row body ever crosses the wire, and this
 * component has no governed string to leak even by accident. The threat model's
 * *"3 memories: …"* preview cannot be written here without first changing the
 * reader — which is the point of putting the restriction in the query rather
 * than in the markup.
 *
 * ## An unreadable category says so
 *
 * `2O-PRIVACY-010` and the owner's decision for this slice both forbid turning
 * a refused read into a zero. A category that could not be counted renders the
 * word, not the number, and the section explains the distinction once rather
 * than per row.
 *
 * ## The withheld tables are shown as withheld
 *
 * Three tables in the deletion enumeration are not readable by the account.
 * Listing them with their reason is what keeps `2O-PRIVACY-002`'s claim honest:
 * the categories cover the deletion enumeration, and the three that are not
 * counted are named rather than quietly dropped.
 *
 * ## Deletion is reached, never performed here
 *
 * `2O-PRIVACY-008` requires deletion to keep every property it has, so this is
 * a link to the page that asks properly — the same call `AccountDataSection`
 * made, for the same reason: an irreversible action one click from a
 * preferences list is what `SH-DELETE-002`'s confirmation and re-authentication
 * exist to prevent.
 */
export function PrivacySection({
  locale,
  census,
  email,
}: {
  locale: Locale;
  census: PrivacyCensus;
  email: string | null;
}) {
  const copy = getPrivacyCopy(locale);
  const unenforced = hasUnenforcedWindow();

  return (
    <section className="data-ai-section" aria-labelledby="privacy-heading">
      <h2 id="privacy-heading">{copy.title}</h2>
      <p className="data-ai-intro">{copy.intro}</p>

      <h3>{copy.census.heading}</h3>
      <p className="data-ai-intro">{copy.census.lead}</p>
      <ul className="privacy-census">
        {PRIVACY_CATEGORIES.map((category) => {
          const entry = census.categories.find((candidate) => candidate.key === category.key);
          return (
            <li key={category.key}>
              <strong>{copy.census.categories[category.key]}</strong>
              <span>
                {entry?.status === "counted"
                  ? copy.census.rowsLabel(entry.rows)
                  : copy.census.unreadable}
              </span>
              {category.surface ? (
                <Link href={getNavigationHref(locale, category.surface)}>
                  {copy.census.seeSurface}
                </Link>
              ) : (
                <span className="privacy-census-nosurface">{copy.census.noSurface}</span>
              )}
            </li>
          );
        })}
      </ul>
      {census.unreadableCategories > 0 ? (
        <p role="status" className="privacy-unreadable">
          {copy.census.unreadableExplained}
        </p>
      ) : null}

      <h3>{copy.census.withheldHeading}</h3>
      <p className="data-ai-intro">{copy.census.withheldLead}</p>
      <ul className="privacy-withheld">
        {WITHHELD_TABLES.map((entry) => (
          <li key={entry.table}>
            <code>{entry.table}</code> — {copy.census.withheldReasons[entry.reason]}
          </li>
        ))}
      </ul>

      <h3>{copy.export.heading}</h3>
      <p className="data-ai-intro">{copy.export.lead}</p>
      <ExportControl locale={locale} />

      {/*
        `2O-PRIVACY-007`. The retention posture the product already publishes,
        reachable from the preferences centre for the first time: `retention.ts`
        has been in the tree since SH.6 with **no consumer at all**, which is the
        producer-with-no-consumer shape this repository has paid for twice.

        Every line is generated by `retentionLine` from `RETENTION_SCHEDULE`, so
        the copy cannot drift from the schedule, and the honesty gate is
        `hasUnenforcedWindow()` — where no sweep runs, the page says the period
        is the policy rather than the practice. **No sweep is scheduled here**:
        `R-2O-22` puts that in an operator script, and scheduling is
        authorization.
      */}
      <h3>{copy.retention.heading}</h3>
      <p className="data-ai-intro">{copy.retention.lead}</p>
      {unenforced ? (
        <p role="note" className="privacy-unenforced">
          {copy.retention.unenforced}
        </p>
      ) : null}
      <ul className="privacy-retention">
        {RETENTION_SCHEDULE.map((entry) => (
          <li key={entry.id}>{retentionLine(locale, entry)}</li>
        ))}
      </ul>
      <p className="privacy-retained-fields">
        {copy.retention.deletionKeeps}: {DELETION_RETAINED_FIELDS.join(", ")}
      </p>

      <h3>{copy.sessions.heading}</h3>
      <p>{email === null ? copy.sessions.signedInUnnamed : copy.sessions.signedInAs(email)}</p>
      <p className="data-ai-intro">{copy.sessions.lead}</p>
      <GlobalSignOut locale={locale} />

      <h3>{copy.deletion.heading}</h3>
      <p className="data-ai-intro">{copy.deletion.lead}</p>
      <Link className="data-ai-door" href={`/${locale}/account/delete`}>
        {copy.deletion.action}
      </Link>
    </section>
  );
}
