export type InterpretationLocale = "pt-BR" | "en";

export const conceptOptions = [
  "raw_record",
  "completed_activity",
  "task",
  "subtask",
  "reminder",
  "appointment",
  "reference",
  "decision",
  "idea",
  "person_note",
  "project_note",
  "pending_question",
  "blocker",
  "dependency",
  "status_update",
  "lasting_preference",
  "personal_memory",
  "request_received",
  "waiting_for_third_party",
] as const;

const copy = {
  "pt-BR": {
    correct: "Corrigir interpretação",
    cancel: "Cancelar correção",
    save: "Salvar nova versão",
    saving: "Salvando…",
    summary: "Resumo",
    occurredAt: "Data e hora do acontecimento (ISO)",
    concepts: "Conceitos",
    entities: "Vínculos",
    dates: "Datas identificadas",
    addDate: "Adicionar data",
    removeDate: "Remover data",
    dateLabel: "Descrição da data",
    classifications: "Classificações",
    reason: "Motivo da correção",
    recordOnly: "Somente registrar, sem executar ações derivadas",
    pending: "Perguntas ainda pendentes",
    keepQuestion: "Manter pergunta",
    undo: "Desfazer última correção",
    undoing: "Desfazendo…",
    reprocess: "Reinterpretar entrada",
    reprocessing: "Enfileirando…",
    noEntities: "Nenhum vínculo disponível.",
  },
  en: {
    correct: "Correct interpretation",
    cancel: "Cancel correction",
    save: "Save new version",
    saving: "Saving…",
    summary: "Summary",
    occurredAt: "Event date and time (ISO)",
    concepts: "Concepts",
    entities: "Links",
    dates: "Identified dates",
    addDate: "Add date",
    removeDate: "Remove date",
    dateLabel: "Date description",
    classifications: "Classifications",
    reason: "Correction reason",
    recordOnly: "Record only, without derived actions",
    pending: "Still-pending questions",
    keepQuestion: "Keep question",
    undo: "Undo latest correction",
    undoing: "Undoing…",
    reprocess: "Reinterpret entry",
    reprocessing: "Queueing…",
    noEntities: "No links available.",
  },
} as const;

export const conceptLabels: Record<(typeof conceptOptions)[number], { "pt-BR": string; en: string }> = {
  raw_record: { "pt-BR": "Registro bruto", en: "Raw record" },
  completed_activity: { "pt-BR": "Atividade concluída", en: "Completed activity" },
  task: { "pt-BR": "Tarefa", en: "Task" },
  subtask: { "pt-BR": "Subtarefa", en: "Subtask" },
  reminder: { "pt-BR": "Lembrete", en: "Reminder" },
  appointment: { "pt-BR": "Compromisso", en: "Appointment" },
  reference: { "pt-BR": "Referência", en: "Reference" },
  decision: { "pt-BR": "Decisão", en: "Decision" },
  idea: { "pt-BR": "Ideia", en: "Idea" },
  person_note: { "pt-BR": "Nota sobre pessoa", en: "Person note" },
  project_note: { "pt-BR": "Nota de projeto", en: "Project note" },
  pending_question: { "pt-BR": "Pergunta pendente", en: "Pending question" },
  blocker: { "pt-BR": "Bloqueio", en: "Blocker" },
  dependency: { "pt-BR": "Dependência", en: "Dependency" },
  status_update: { "pt-BR": "Atualização", en: "Status update" },
  lasting_preference: { "pt-BR": "Preferência", en: "Preference" },
  personal_memory: { "pt-BR": "Memória", en: "Memory" },
  request_received: { "pt-BR": "Pedido recebido", en: "Request received" },
  waiting_for_third_party: { "pt-BR": "Aguardando terceiro", en: "Waiting on someone" },
};

export function getInterpretationCopy(locale: InterpretationLocale) {
  return copy[locale];
}

export const lifecycleLabels = {
  saved: { "pt-BR": "Salva", en: "Saved" },
  interpreting: { "pt-BR": "Interpretando", en: "Interpreting" },
  awaiting_review: { "pt-BR": "Aguardando revisão", en: "Awaiting review" },
  partially_processed: { "pt-BR": "Processada parcialmente", en: "Partially processed" },
  completed: { "pt-BR": "Concluída", en: "Completed" },
  recoverable_error: { "pt-BR": "Falha recuperável", en: "Recoverable failure" },
  terminal_error: { "pt-BR": "Falha definitiva", en: "Terminal failure" },
  reprocessing: { "pt-BR": "Reinterpretando", en: "Reinterpreting" },
} as const;
