/**
 * The untrusted boundary between M3 and the product.
 *
 * `apply_entity_deletion` and its two siblings return `jsonb`, which arrives in
 * TypeScript as `unknown`. The engineering standard is that every untrusted
 * boundary is parsed rather than cast, and a database function is one of the
 * named boundaries — not because the database is hostile, but because a schema
 * that drifts from its caller should fail at the parse with a message, rather
 * than three frames later as `undefined` rendered into a sentence about how
 * many relations are about to be destroyed.
 *
 * The consequence counts are `int().nonnegative()` rather than `number()`: a
 * negative or fractional count is not a number the preview should ever print,
 * and this is the only place that can say so.
 */

import { z } from "zod";

import { CONSEQUENCE_KEYS, DELETABLE_ENTITY_TYPES, RETENTION_KINDS } from "./contracts";

const countSchema = z.number().int().nonnegative();

/**
 * All eleven keys are `required`. That is deliberate and it mirrors the
 * function: the digest the confirmation binds is taken over this whole object,
 * so a key that could be absent would let two different states hash alike.
 */
export const consequencesSchema = z.object(
  Object.fromEntries(CONSEQUENCE_KEYS.map((key) => [key, countSchema])) as Record<
    (typeof CONSEQUENCE_KEYS)[number],
    typeof countSchema
  >,
);

export const deletionPreviewSchema = z.object({
  entityType: z.enum(DELETABLE_ENTITY_TYPES),
  entityId: z.string().uuid(),
  consequences: consequencesSchema,
  undoAvailable: z.boolean(),
  retention: z.array(z.enum(RETENTION_KINDS)),
});

/**
 * The issuance response is the preview plus the confirmation's id.
 *
 * The id is returned so the surface can show that a confirmation exists, and
 * for **nothing else**: it is not an argument to the apply, which resolves the
 * row itself by `(auth.uid(), operation_key)`. A client that held the id could
 * not use it to authorize anything, which is the property that keeps the
 * confirmation from becoming portable.
 */
export const deletionConfirmationSchema = deletionPreviewSchema.extend({
  confirmationId: z.string().uuid(),
});

export const deletionResultSchema = z.object({
  deleted: z.literal(true),
  entityType: z.enum(DELETABLE_ENTITY_TYPES),
  entityId: z.string().uuid(),
  consequences: consequencesSchema,
  undoId: z.string().uuid(),
  undoExpiresAt: z.string(),
  replayed: z.boolean().optional(),
});

export const undoResultSchema = z.object({
  undone: z.literal(true),
  affected: z.number().int().nonnegative(),
  entityType: z.enum(DELETABLE_ENTITY_TYPES).optional(),
});

export type ParsedDeletionPreview = z.infer<typeof deletionPreviewSchema>;
export type ParsedDeletionConfirmation = z.infer<typeof deletionConfirmationSchema>;
export type ParsedDeletionResult = z.infer<typeof deletionResultSchema>;

/**
 * The form input, validated before anything reaches the database.
 *
 * `operationKey` is generated by the surface and echoed back on the apply, so
 * the two halves of one deliberate act share an idempotency key. It is **not**
 * authorization — the confirmation row is — which is why an attacker-chosen key
 * buys nothing: it selects among the caller's own confirmations and no others.
 */
export const deletionRequestSchema = z.object({
  entityType: z.enum(DELETABLE_ENTITY_TYPES),
  entityId: z.string().uuid(),
  operationKey: z.string().min(8).max(240),
  locale: z.enum(["pt-BR", "en"]).optional(),
});
